### ISSUE TITLE
Weird behavior when using bomb bay multiple times

### ISSUE THREAD

**Issue by mxnmnm** [Loreb29/nuke-bay#1]
I'm playing on a server and I tested this mod in creative mode and survival. Sometimes it lets me drop multiple bombs in a row, other times it just stops dropping any. Is this intended behavior? If so what limits you from dropping more?

**Comment by Loreb29** [comment]
The weapon is supposed to shoot a nuke with a delay of 450 ticks between each dropped nuke, but it's not supposed to shoot many nukes in a row. although, due to it mimicking the behaviour of the default Bomb Bay, 1 used ammo could be able to produce many nukes.
Did you have a problem with the delay being ignored, or just being able to drop more than one with the delay?.
Although, if you are refering to the default Bomb Bay, it is intended behavior.

**Comment by mxnmnm** [comment]
Sometimes the delay would be ignored and let you spam bombs. Other times the delay seemed to not end and you could not drop anymore bombs. Maybe I didn't wait long enough, but it just wasn't consistent

**Comment by Loreb29** [comment]
Do you get this issue/can reproduce it when playing in singleplayer?

**Comment by mxnmnm** [comment]
I don't

**Comment by Loreb29** [comment]
Does this issue also exist with other Immersive Aircraft weapons?, like the default Bomb Bay, for example.
Since it doesn't seem to exist in single player, it could be a product of latency and the way the server handles the ticks.

**Comment by mxnmnm** [comment]
It didn't happen with other weapon types, but I will note that this was on the older version before immersive aircraft updated so maybe when I update that'll change things?
